apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: CP4I-lc
  owner: CP4I-lc
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/CP4I-lc/multi-tenancy-gitops-apps.git
